services:
  postgres:
    image: postgres:latest
    container_name: postgres-db-projeto-g6
    restart: always
    env_file:
      - '.env'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
